### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by bengeois** [rhiever/TwitterFollowBot#109]
Hello,

I want to run this instance 

`from TwitterFollowBot import TwitterBot

my_bot = TwitterBot()
my_bot.sync_follows()
my_bot.auto_rt("LunetiersCreateurs", count=5)`

But I get this error : from TwitterFollowBot import TwitterBot
  File "C:\Users\Shift\Desktop\TwitterFollowBot-master\TwitterFollowBot__init__.py", line 21, in <module>
    from twitter import Twitter, OAuth, TwitterHTTPError
ImportError: cannot import name Twitter

How can I fix this ?

Thanks

**Comment by hichamzouarhi** [comment]
you have to install twitter first 

`pip install twitter`
