### ISSUE TITLE
Add a method to reply to a message

### ISSUE THREAD

**Issue by teopost** [rhiever/TwitterFollowBot#34]
It would be useful to have a method to reply to a message

**Comment by rhiever** [comment]
:+1: This is far outside my personal use case for the bot, so I likely won't develop this feature, but I encourage someone to develop it and send in a PR.

**Comment by teopost** [comment]
OK @rhiever , I understand. Thank's

**Comment by Yutsa** [comment]
Do you want to be able to reply to a specific tweet ?
I made a method to search tweets with specific keyword or hashtag and then reply to these tweets.
If you are interested I could share it.

**Comment by rhiever** [comment]
Sure - could you please submit a PR so we can see what it looks like?

**Comment by Yutsa** [comment]
Ok, PR done.
