### ISSUE TITLE
how run this on server?

### ISSUE THREAD

**Issue by vallez01** [rhiever/TwitterFollowBot#37]
how run this on server?
like bot using php 
thx

**Comment by rhiever** [comment]
I recommend setting it up as a cron job on the server:
en.m.wikipedia.org/wiki/Cron

That way you can have the bot run  certain scripts at certain points of the
day to perform various automated actions.

On Monday, May 25, 2015, vallez01 <notifications@github.com> wrote:

> how run this on server?
> like bot using php
> thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/37>.
>


-- 
Randal S. Olson, Ph.D.

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com
