### ISSUE TITLE
Retweet: Number of Hashtags & Number of Mentions

### ISSUE THREAD

**Issue by LouisXavier** [rhiever/TwitterFollowBot#39]
Hi,

I'm currently trying to see if we could add conditions to the retweet bot to enhance quality of retweets.

If we wanted to limit the number of hashtags in the tweet before retweeting and the number of mentions, how would you go about it?

Thanks for your help!!
LX

**Comment by rhiever** [comment]
You'd have to edit the auto RT source code. You could grab the message of the tweet and count the number of hashtags and make a decision to RT based off of that.
