### ISSUE TITLE
Getting A no module name twitter error

### ISSUE THREAD

**Issue by gomd139** [rhiever/TwitterFollowBot#41]
this is what I'm getting

Traceback (most recent call last):
  File "/Users/jeremyyoung/Desktop/TwitterFollowBot-master/TwitterFollowBot/__init__.py", line 21, in <module>
    from twitter import Twitter, OAuth, TwitterHTTPError
ImportError: No module named 'twitter

Any Help?

**Comment by rhiever** [comment]
You need to install the Twitter API library: pip install twitter

On Sunday, June 7, 2015, gomd139 <notifications@github.com> wrote:

> this is what I'm getting
>
> Traceback (most recent call last):
> File "/Users/jeremyyoung/Desktop/TwitterFollowBot-master/TwitterFollowBot/
> *init*.py", line 21, in
> from twitter import Twitter, OAuth, TwitterHTTPError
> ImportError: No module named 'twitter
>
> Any Help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/41>.
>


-- 
Randal S. Olson, Ph.D.

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by gomd139** [comment]
I'm using a macbook and i ran that i my terminal command line and i recieved:

Requirement already satisfied (use --upgrade to upgrade): twitter in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Jeremys-Air:~ jeremyyoung$

**Comment by gomd139** [comment]
however I still get that error message

**Comment by rhiever** [comment]
Try the --upgrade command as well like it suggested. If that doesn't work,
uninstall and reinstall all of the packages - there's some sort of weird
package linkage error going on, I think. I couldn't reproduce this locally
on my Mac.


On Sunday, June 7, 2015, gomd139 <notifications@github.com> wrote:

> however I still get that error message
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/41#issuecomment-109813051>
> .
>


-- 
Randal S. Olson, Ph.D.

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by rhiever** [comment]
Any progress with this?

**Comment by patricmutwiri** [comment]
Install all the dependencies first. One by one, error by error.
