### ISSUE TITLE
Bot not running

### ISSUE THREAD

**Issue by john023** [rhiever/TwitterFollowBot#42]
Hi, whenever I try to run the bot I get the following error:
```python
Traceback (most recent call last):
  File "my_bot.py", line 1, in <module>
    from TwitterFollowBot import TwitterBot
  File "/home/TwitterFollowBot-master/TwitterFollowBot/__init__.py", line 99
    "before continuing.", file=sys.stderr)
                              ^
SyntaxError: invalid syntax
```
Any idea why this is happening?

**Comment by rhiever** [comment]
Are you running it on Python 2? On your command line, type:

    python --version

On Tue, Jun 9, 2015 at 4:24 PM, john023 <notifications@github.com> wrote:

> Hi, whenever I try to run the bot I get the following error:
>
> Traceback (most recent call last):
>   File "my_bot.py", line 1, in <module>
>     from TwitterFollowBot import TwitterBot
>   File "/home/TwitterFollowBot-master/TwitterFollowBot/__init__.py", line 99
>     "before continuing.", file=sys.stderr)
>                               ^SyntaxError: invalid syntax
>
> Any idea why this is happening?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/42>.
>



-- 
Randal S. Olson, Ph.D.

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by john023** [comment]
I am running Python 2.7.9

**Comment by rhiever** [comment]
Huh. I think the Python 2 print statements don't take that `file` parameter to the `print` statements: https://github.com/rhiever/TwitterFollowBot/blob/master/TwitterFollowBot/__init__.py#L99

You can either remove those `file` parameters from the `print` statements to fix it, or upgrade to Python 3. I recommend the latter.

**Comment by rhiever** [comment]
Another option is to run v1.0 of the bot, which should run fine on Python 2: https://github.com/rhiever/TwitterFollowBot/releases/tag/v1.0

but doesn't have the latest features.
