### ISSUE TITLE
sync_follows() problem

### ISSUE THREAD

**Issue by herczogzoltan** [rhiever/TwitterFollowBot#44]
Hey buddy! I get this error message:

Traceback (most recent call last):
  File "twitterbot.py", line 10, in <module>
    my_bot.sync_follows()
  File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/__init__.py", line 122, in sync_follows
    followers_status = self.TWITTER_CONNECTION.followers.ids(screen_name=self.BOT_CONFIG["TWITTER_HANDLE"])
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 308, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 341, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 404 for URL: 1.1/followers/ids.json using parameters: (oauth_consumer_key= 

and then it shows my datas.

I also noticed that I can't force follow users by adding their twitter IDs' in the config file.

What i did:

uninstalled and installed again "twitter" and "TwitterFollowBot".

Hope you have some idea. :)

**Comment by rhiever** [comment]
Hey @herczogzoltan!

>I also noticed that I can't force follow users by adding their twitter IDs' in the config file.

The config file doesn't allow you to force follow people by listing their IDs in it; rather, the config file ID list is a list of IDs that the bot won't unfollow once you follow them.

The error it's spitting out seems to be telling me that it's not finding your Twitter username. Do you have your Twitter username entered into the config file, case-sensitive?

**Comment by herczogzoltan** [comment]
Hello @rhiever !

1. Thanks for the information, now I get what it means! :)
2. Yes I did, but unfortunately I wrote a little "@" before my username, now it works, thanks for the rapidly fast answer!

**Comment by rhiever** [comment]
:+1:
