### ISSUE TITLE
Some suggestions that may be interesting. 

### ISSUE THREAD

**Issue by Lincete** [rhiever/TwitterFollowBot#47]
Hello!, I am really new coding python but  I got some ideas you may like.

 I Saw that 
``` auto_unfollow_nonfollowers(): ``` deletes all the nonfollowers but if you do ```auto_follow``` often maybe you follow so much people that wouldnt follow you back and its so agressive, so I figured a way to prevent that only changing the definition and one line.``` def auto_unfollow_nonfollowers(self,count=None):```
 and  just before the file writings and unfollowing ```not_following_back = not_following_back[:count] ``` 
So if you dont set the count the bot will work normal and if you set it will go only on the interval, so you dont hit rate limits.

**Comment by rhiever** [comment]
Good idea - `auto_unfollow_nonfollowers()` should have a limiting variable like that too. I filed this as an enhancement request.
