### ISSUE TITLE
Update the package on PyPi

### ISSUE THREAD

**Issue by mgoodfellow** [rhiever/TwitterFollowBot#53]
Hi,

Is it possible to issue a new release of the package with the latest PRs included?

Thanks!

**Comment by rhiever** [comment]
Yes, I've been meaning to do that soon.

On Tuesday, July 7, 2015, Mike Goodfellow <notifications@github.com> wrote:

> Hi,
>
> Is it possible to issue a new release of the package with the latest PRs
> included?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/53>.
>


-- 
Randal S. Olson, Ph.D.

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by rhiever** [comment]
Done.

**Comment by ecolell** [comment]
side-topic: @rhiever It could be cool if you also append a tag with the same version into the git repository.

**Comment by rhiever** [comment]
https://github.com/rhiever/TwitterFollowBot/releases/tag/v2.0.1

Let me know if every looks fine with the latest release. I probably shouldn't be doing a new release in the middle of SciPy. :-)

**Comment by ecolell** [comment]
:+1: It looks perfect! :smiley:
