### ISSUE TITLE
Creating an instance

### ISSUE THREAD

**Issue by andreasdiehl** [rhiever/TwitterFollowBot#57]
What does "creating an instance" mean?

**Comment by rhiever** [comment]
I was about to write an explanation, but instead I'll link to a better explanation [here](http://www.quora.com/What-is-meant-by-instance-of-a-class-and-instance-variables-in-Java).

**Comment by andreasdiehl** [comment]
Thx. Though I`m still missing the context. I think what I`d require is a manual. I managed to get the library installed, I also can create a twitter app, add credentials to the config. After this step I`m lost.:)

**Comment by rhiever** [comment]
The [README}(https://github.com/rhiever/TwitterFollowBot/blob/master/README.md) is the closest thing we have to a manual. :-)

Once you have the credentials added to the config, and you create an instance of the bot pointing to that credentials file, you should be able to copy-and-paste the code snippets from the README as you need.

Creating an instance of the bot pointing to that credentials file works differently depending on your OS. If you're on Windows, you'd do something like:

    my_bot = TwitterBot('C:/Documents/config.txt') # or wherever your config.txt is

if you're on Unix, Linux, or a Mac, you'd do something like:

    my_bot = TwitterBot('~/Documents/config.txt') # or wherever your config.txt is

**Comment by andreasdiehl** [comment]
Thanks for your help. And your patience.:) I went through README as well, the point is I just don`t know where to start. "Creating in instance" doesn`t mean anything to me, even if I might get the overall meaning. What do I have to do to create my first own bot? Do I have to create a new file? Edit an existing file? If so which one? Is each bot an own file? What is the meaning of the _init_.py file Those are the questions I`m struggling with.

**Comment by tatic0** [comment]
Hello, 

This is a really fine piece of code. I've been using it for the last days.
With the README and very little googling, it was quite straightforward to put the bot in production in a Raspberry Pi.

If it can help, I would gladly write a HOWTO made mostly from the `history` of my term and very little prose.

Regards,

Francisco

**Comment by andreasdiehl** [comment]
@tatic0 a HOWTO would for me definitively be a help. Most helpful for me is an tutorial that teaches very concrete step by step what to do (on a level of "next create a new file", "put it to the folder xxx" etc.)

**Comment by rhiever** [comment]
Sure - I would like to see what a tutorial written from your perspective
would look like. Thank you.

On Sunday, July 12, 2015, f varas <notifications@github.com> wrote:

> Hello,
>
> This is a really fine piece of code. I've been using it for the last days.
> With the README and very little googling, it was quite straightforward to
> put the bot in production in a Raspberry Pi.
>
> If it can help, I would gladly write a HOWTO made mostly from the history
> of my term and very little prose.
>
> Regards,
>
> Francisco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/57#issuecomment-120700407>
> .
>


-- 
Randal S. Olson, Ph.D.

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by Domebone** [comment]
Hello im getting an index error when i try to create an instance of the bot, any thoughts?

**Comment by rhiever** [comment]
@Domebone: I'll need to see the code you were using that raised the error and the actual error message to have a chance of guessing what it is.

**Comment by Domebone** [comment]
>>> my_bot = TwitterBot('C:\Users\Ryszard\Desktop\TwitterFollowBot-master\Twitte
rFollowBot-master\config.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\TwitterFollowBot\__init__.py", line 38, in
 __init__
    self.bot_setup(config_file)
  File "C:\Python27\lib\site-packages\TwitterFollowBot\__init__.py", line 50, in
 bot_setup
    with open(config_file, "r") as in_file:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Ryszard\\Desktop\\Twit
terFollowBot-master\\TwitterFollowBot-master\\config.txt'
>>>

**Comment by rhiever** [comment]
@Domebone: Looks like you need to create a `config.txt` file in the location you're pointing it to. Are you sure that's the right directory?

**Comment by tatic0** [comment]
Hello All, 

This weekend I'll maybe find some time to write a Howto.
Please be patient :)

Regards,

**Comment by Domebone** [comment]
@tatic0 awesome! and @rhiever yes i dont know why it wouldnt work, the config.txt is there and it has the Oauth tokens, is there any step i might have messed up before that could cause this?

**Comment by rhiever** [comment]
The only thing I can think of is that the directory string has `TwitterFollowBot-master` twice on there. Maybe try removing one of them.

**Comment by tatic0** [comment]
Hello, 

The first draf of the Howto is ready, I'm still working on it, there's still some work to do:

You can read it here:
https://docs.google.com/document/d/16hsuixvcz7x2rKpOpZL1uKJhMixqFshYbXCX9XiIoG4/edit?usp=sharing

@rhiever If you find the howto good enough, I can put it on the Wiki section of this project.
I'd like to put it in my blog if you agree.

**Comment by Domebone** [comment]
@tatic0 being new to this, I have no idea what your how to means compared to the wiki, could you make it more beginner friendly?

**Comment by kenncann** [comment]
I had a similar problem. If you named your text file 'config.txt' rather than just 'config' then change it from the former to the later.
