### ISSUE TITLE
auto_unfollow_nonfollowers() error

### ISSUE THREAD

**Issue by JSTQ** [rhiever/TwitterFollowBot#61]
Choosing time between 10 and 60 - waiting 31 seconds before action
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\twitter\api.py", line 315, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start_bot_unfollow.py", line 4, in <module>
    my_bot.auto_unfollow_nonfollowers()
  File "C:\Python34\twitterfollowbot\TwitterFollowBot\__init__.py", line 426, in auto_unfollow_nonfollowers
    self.TWITTER_CONNECTION.friendships.destroy(user_id=user_id)
  File "C:\Python34\lib\site-packages\twitter\api.py", line 308, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "C:\Python34\lib\site-packages\twitter\api.py", line 341, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 403 for URL: 1.1/friendships/destroy.json using parameters: (oauth_consumer_key=TPG0beLUoVv5C71nWWnfJCkg3&oaut
h_nonce=10443273249529987898&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1437903876&oauth_token=3371608815-Fg5J2wc4mHkus8RwVWE9XLmf92PmU9IkPF25P7V&oauth_ve
rsion=1.0&user_id=1427030012&oauth_signature=XmL3f49B4DkOKLPYncqg2JYbS34%3D)
details: {'errors': [{'code': 261, 'message': 'Application cannot perform write actions. Contact Twitter Platform Operations through https://support.twitter.com
/forms/platform'}]}

Line 426 in init.py is 
self.TWITTER_CONNECTION.friendships.destroy(user_id=user_id)

**Comment by rhiever** [comment]
Here's the important part of the errpr message:

>{'errors': [{'code': 261, 'message': *'Application cannot perform write
actions. *Contact Twitter Platform Operations through
https://support.twitter.com
/forms/platform'}

You were performing too many write actions (follow, fav, unfollow, etc.)
and Twitter suspended your application account. You can make a new one, but
beware...

On Sun, Jul 26, 2015 at 5:46 AM, JSTQ <notifications@github.com> wrote:

> Choosing time between 10 and 60 - waiting 31 seconds before action
> Traceback (most recent call last):
> File "C:\Python34\lib\site-packages\twitter\api.py", line 315, in
> _handle_response
> handle = urllib_request.urlopen(req, *
>
>
>
>
>
>
>
> *kwargs) File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
> return opener.open(url, data, timeout) File
> "C:\Python34\lib\urllib\request.py", line 469, in open response = meth(req,
> response) File "C:\Python34\lib\urllib\request.py", line 579, in
> http_response 'http', request, response, code, msg, hdrs) File
> "C:\Python34\lib\urllib\request.py", line 507, in error return
> self._call_chain(*args)
> File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
> result = func(*args)
> File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
> raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
> File "start_bot_unfollow.py", line 4, in
> my_bot.auto_unfollow_nonfollowers()
> File "C:\Python34\twitterfollowbot\TwitterFollowBot__init__.py", line 426,
> in auto_unfollow_nonfollowers
> self.TWITTER_CONNECTION.friendships.destroy(user_id=user_id)
> File "C:\Python34\lib\site-packages\twitter\api.py", line 308, in *call*
> return self._handle_response(req, uri, arg_data, _timeout)
> File "C:\Python34\lib\site-packages\twitter\api.py", line 341, in
> _handle_response
> raise TwitterHTTPError(e, uri, self.format, arg_data)
> twitter.api.TwitterHTTPError: Twitter sent status 403 for URL:
> 1.1/friendships/destroy.json using parameters:
> (oauth_consumer_key=TPG0beLUoVv5C71nWWnfJCkg3&oaut
>
> h_nonce=10443273249529987898&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1437903876&oauth_token=3371608815-Fg5J2wc4mHkus8RwVWE9XLmf92PmU9IkPF25P7V&oauth_ve
>
> rsion=1.0&user_id=1427030012&oauth_signature=XmL3f49B4DkOKLPYncqg2JYbS34%3D)
> details: {'errors': [{'code': 261, 'message': 'Application cannot perform
> write actions. Contact Twitter Platform Operations through
> https://support.twitter.com
> /forms/platform'}]}
>
> Line 426 in init.py is
> self.TWITTER_CONNECTION.friendships.destroy(user_id=user_id)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/61>.
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com
