### ISSUE TITLE
Keep getting rate limited

### ISSUE THREAD

**Issue by jbarne06** [rhiever/TwitterFollowBot#62]
Hello!

I've been playing with TwitterFollowBot to favorite Tweets, but keep having issues getting rate limited. 

Am I using it properly? Here's the code I'm using:

from TwitterFollowBot import TwitterBot

my_bot = TwitterBot()

while True:
    my_bot.auto_fav("#FalloutShelter", count=100)
    wait(3600)

**Comment by rhiever** [comment]
I think Twitter is becoming increasingly strict about automated fav/follow
actions. You may have to make the bot wait several hours in between each
auto_fav action. It may also help to have your bot wait a random amount of
time in between each action:
https://github.com/rhiever/TwitterFollowBot#configuring-the-bot

On Mon, Jul 27, 2015 at 8:58 PM, jbarne06 <notifications@github.com> wrote:

> Hello!
>
> I've been playing with TwitterFollowBot to favorite Tweets, but keep
> having issues getting rate limited.
>
> Am I using it properly? Here's the code I'm using:
>
> from TwitterFollowBot import TwitterBot
>
> my_bot = TwitterBot()
>
> while True:
> my_bot.auto_fav("#FalloutShelter", count=100)
> wait(3600)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/62>.
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by jbarne06** [comment]
Appreciate the swift response, Randy.

Upped the delay to 8 hours. Will report back with results :)

On Mon, Jul 27, 2015 at 9:09 PM, Randy Olson <notifications@github.com>
wrote:

> I think Twitter is becoming increasingly strict about automated fav/follow
> actions. You may have to make the bot wait several hours in between each
> auto_fav action. It may also help to have your bot wait a random amount of
> time in between each action:
> https://github.com/rhiever/TwitterFollowBot#configuring-the-bot
>
> On Mon, Jul 27, 2015 at 8:58 PM, jbarne06 <notifications@github.com>
> wrote:
>
> > Hello!
> >
> > I've been playing with TwitterFollowBot to favorite Tweets, but keep
> > having issues getting rate limited.
> >
> > Am I using it properly? Here's the code I'm using:
> >
> > from TwitterFollowBot import TwitterBot
> >
> > my_bot = TwitterBot()
> >
> > while True:
> > my_bot.auto_fav("#FalloutShelter", count=100)
> > wait(3600)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rhiever/TwitterFollowBot/issues/62>.
> >
>
>
>
> --
> Randal S. Olson, Ph.D.
> Postdoctoral Researcher, Institute for Biomedical Informatics
> University of Pennsylvania
>
> E-mail: rso@randalolson.com | Twitter: @randal_olson
> <https://twitter.com/randal_olson>
> http://www.randalolson.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/62#issuecomment-125398867>
> .
>



-- 
James W. Barnes

jbarne06@gmail.com
248.207.8393

**Comment by jbarne06** [comment]
Looks like 100 favorites is too many at once. Removed the while loop and still got rate limited.

**Comment by rhiever** [comment]
Good to know. It seems to vary between accounts. Sometimes you just need to
tinker with it and see what Twitter will allow you to do.

On Thursday, July 30, 2015, jbarne06 <notifications@github.com> wrote:

> Looks like 100 favorites is too many at once. Removed the while loop and
> still got rate limited.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/62#issuecomment-126404779>
> .
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com
