### ISSUE TITLE
Multiple accounts autofollow and unfollow.

### ISSUE THREAD

**Issue by 179skr** [rhiever/TwitterFollowBot#65]
Hi, could someone show me a file they are using for multiple accounts to autofollow and unfollow aswell as auto retweet certain user and favourite a phase. I am really confused on how to this.

Thanks :D im a noob btw

**Comment by ravindran2454** [comment]
my_bot.auto_follow_follwers_of_user(“senthilcp”,count=30000) 

Should be following all the users of @senthilcp upto 30k. works ?

**Comment by JoSanson** [comment]
I think not, because twitter have some limit, you cant follow more than 1000 users per day.
