### ISSUE TITLE
How to add delay between actions.

### ISSUE THREAD

**Issue by rl421403** [rhiever/TwitterFollowBot#69]
This is my script.

    from TwitterFollowBot import TwitterBot

    my_bot = TwitterBot("config.txt")

    my_bot.auto_follow("wordpress", count=10)

This makes me follow 10 users. And I want to add delay between these follow actions or any other action. 

How can I add that delay.

#### EDIT:

And what are these `FOLLOW_BACKOFF_MIN_SECONDS:10` & `FOLLOW_BACKOFF_MAX_SECONDS:60`.
What exactly both of these do?

**Comment by rhiever** [comment]
`FOLLOW_BACKOFF_MIN_SECONDS:10` and `FOLLOW_BACKOFF_MAX_SECONDS:60` in the config.txt tell the bot to wait a random amount of seconds in between those two numbers between every follow, fav, etc. action. That basically implements the delay you're looking for.

**Comment by rl421403** [comment]
That's nice but I don't think it is working properly. Because when I tried above script, it added followers instantly without even waiting for 10-60 seconds. Command ran for like less then 1 sec.

I have been using default options in my config file.

    FOLLOW_BACKOFF_MIN_SECONDS:10
    FOLLOW_BACKOFF_MAX_SECONDS:60

I have Python 3 installed on Ubuntu server.

**Comment by rhiever** [comment]
That's really strange. I swear the latest version on PyPi has that functionality.

I just did a re-upload to PyPi with v2.0.2. Please try a `pip --upgrade` and let me know if the wait functionality works now. It's working fine on my server.

**Comment by rl421403** [comment]
That could be the issue.
I have Python 3.4.0 installed and pip 1.5.4. I tried upgrading pip but it's keep installing 1.5.4.

and `pip --upgrade` returns invalid command.

**Comment by rhiever** [comment]
Try:

    pip install --upgrade TwitterFollowBot

On Tue, Aug 11, 2015 at 10:17 AM, Robert Hue <notifications@github.com>
wrote:

> That could be the issue.
> I have Python 3.4.0 installed and pip 1.5.4. I tried upgrading pip but
> it's keep installing 1.5.4.
>
> and pip --upgrade returns invalid command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/69#issuecomment-129898825>
> .
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by rl421403** [comment]
Oh you mean upgrade TwitterFollowBot. I thought you are asking to upgrade about pip.
Anyway, I upgraded TwitterFollowBot and strange thing happened. it started adding random delay.

Earlier when I executed my script, I got output like...

    Followed 98918919
    Followed 29382938
    Followed 29389238

And it took less then a minute to follow 3 accounts but now it's seems to be working. This is the output I got.

    Choosing time between 10 and 60 - waiting 11 seconds before action
    Followed 98918919
    Choosing time between 10 and 60 - waiting 44 seconds before action
    Followed 29382938
    Choosing time between 10 and 60 - waiting 53 seconds before action
    Followed 29389238

Yep.. It's working great now. Thanks for your help. Really nice script.

**Comment by rhiever** [comment]
Great!

You can control the range of that delay with the `FOLLOW_BACKOFF_MIN_SECONDS` and `FOLLOW_BACKOFF_MAX_SECONDS` in your config.txt too.

If you want to remove the delay entirely, then simply remove those two entries in your config.txt.
