### ISSUE TITLE
Strange Error Message when bot is ran value=line[1].strip() out of range

### ISSUE THREAD

**Issue by xSLM** [rhiever/TwitterFollowBot#70]
Well I just finished the installation process and all of that and when I run the bot it comes up with an error message saying this:

![image](https://cloud.githubusercontent.com/assets/13797965/9274947/bb9326de-4291-11e5-8b93-6177149240f3.png)

Im not sure why I tried to investigate it and got nowhere. Help!!

my bot looks like this if you need to know:

![image](https://cloud.githubusercontent.com/assets/13797965/9274958/cefc08da-4291-11e5-8c11-fc7f5956229a.png)

**Comment by xSLM** [comment]
Im getting this error still ^^^

**Comment by rhiever** [comment]
We'll keep discussion of this issue to #71
