### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by dwfz** [rhiever/TwitterFollowBot#74]
![image](https://cloud.githubusercontent.com/assets/14083792/9620834/a656ccd4-50ed-11e5-9e1b-05df54cee330.png)

Sorry if this is a dumb question, but how do I fix this error?

**Comment by rhiever** [comment]
I see you closed the issue; did you fix it?

**Comment by rhiever** [comment]
If you didn't fix it, please copy and paste your config.txt here. Make sure to remove your API keys.

**Comment by dwfz** [comment]
OAUTH_TOKEN:
AUTH_SECRET:
CONSUMER_KEY:
CONSUMER_SECRET:
TWITTER_HANDLE:
ALREADY_FOLLOWED_FILE:already-followed.txt
FOLLOWERS_FILE:followers.txt
FOLLOWS_FILE:following.txt
USERS_KEEP_FOLLOWING:
USERS_KEEP_UNMUTED:
USERS_KEEP_MUTED:
FOLLOW_BACKOFF_MIN_SECONDS:10
FOLLOW_BACKOFF_MAX_SECONDS:60

**Comment by rhiever** [comment]
There's something weird with your API keys then. Email me the config.txt please: rso@randalolson.com

**Comment by dwfz** [comment]
fixed it, had to make the the string raw and had a problem with the naming of the file. Thanks for the quick responses dude
