### ISSUE TITLE
rate limit 

### ISSUE THREAD

**Issue by dwfz** [rhiever/TwitterFollowBot#75]
can anybody tell me what the probationary time is before you can fav more tweets after being rate limited?

**Comment by rhiever** [comment]
15 minutes IIRC.

On Mon, Sep 7, 2015 at 12:02 AM, dwfz <notifications@github.com> wrote:

> can anybody tell me what the probationary time is before you can fav more
> tweets after being rate limited?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/75>.
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com
