### ISSUE TITLE
seemingly idle  

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [rhiever/TwitterFollowBot#81]
I keep getting this, running inside a virtual environment.. 
<pre><code>
Choosing time between 10 and 60 - waiting 53 seconds before action
</code></pre>
no matter what tests I do.. am I doing something wrong? 

this is my code 
<pre><code>
from TwitterFollowBot import TwitterBot
my_bot = TwitterBot()

# sync to use less API time
my_bot.sync_follows()

my_bot.auto_rt("#node", count=5)
</code></pre>

**Comment by rhiever** [comment]
Change the

    FOLLOW_BACKOFF_MIN_SECONDS:10
    FOLLOW_BACKOFF_MAX_SECONDS:60

in your `config.txt` to a small value. It's important to have a short delay so you don't quickly hit the API rate limit.

**Comment by Karlheinzniebuhr** [comment]
ok my problem is that nothing happens, I follow myself and tweet with the keywords but no reaction.. 
is there a way to get a more verbose log, to detect possible errors? 
![image](https://cloud.githubusercontent.com/assets/5278928/9978947/626619fe-5f1f-11e5-8c06-4ca5c4300359.png)

**Comment by rhiever** [comment]
The code for `auto_rt` is here: https://github.com/rhiever/TwitterFollowBot/blob/master/TwitterFollowBot/__init__.py#L255

It actually shouldn't be waiting (bug in #77) on an auto_rt, so I don't know what's going on there. I advise digging into the code.

**Comment by Reclamator** [comment]
it works now, I suggest reducing the default depth from 100 to 10 or 20 though, with 100 the rate limit is reached within 30 seconds..

**Comment by Karlheinzniebuhr** [comment]
it works now, I suggest changing the count from 100 to 10 and having random delay similar to this
<code><pre>
	def check():
		print('checking')
		my_bot.auto_add_to_list("#TwitterBot", "twitterbot-list", count=10)
		delay = randint(30, 120)
		print('waiting '+str(delay)+' seconds..')
		threading.Timer(delay, check).start()
	check()
</pre></code>

this prevents rate limiting for me very nicely..
