### ISSUE TITLE
Error when trying to 'my_bot = TwitterBot()'

### ISSUE THREAD

**Issue by K00sKlust** [rhiever/TwitterFollowBot#82]
Hey. Im have been using the TwitterFollowBot for a few days, and its amazing :) :+1: But now i got this error out of nothing. :confused: Am i doing something wrong? (sorry for my bad english sometimes)

> root@EeePcServer:/home/user/PythonScrypts/Twitterbot# python
> 
> Python 2.7.6 (default, Jun 22 2015, 18:00:18)
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> '>>>from TwitterFollowBot import TwitterBot
> '>>>my_bot = TwitterBot()

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/__init__.py", line 42, in __init__
>     self.bot_setup(config_file)
>   File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/__init__.py", line 82, in bot_setup
>     value = line[1].strip()
> IndexError: list index out of range

config.txt (but i dont think thats the problem)
> OAUTH_TOKEN:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> OAUTH_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> CONSUMER_KEY:xxxxxxxxxxxxxxxxxxxxxxxxxx
> CONSUMER_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> TWITTER_HANDLE:xxxxxxxx
> ALREADY_FOLLOWED_FILE:already-followed.txt
> FOLLOWERS_FILE:followers.txt
> FOLLOWS_FILE:following.txt
> USERS_KEEP_FOLLOWING:
> USERS_KEEP_UNMUTED:
> USERS_KEEP_MUTED:
> FOLLOW_BACKOFF_MIN_SECONDS:3
> FOLLOW_BACKOFF_MAX_SECONDS:10

I got around 1200 followers right now. Just trying to give usefull information :)

**Comment by rhiever** [comment]
Here's where it's throwing the error:
https://github.com/rhiever/TwitterFollowBot/blob/master/TwitterFollowBot/__init__.py#L82

That's when it's trying to read the config file. Every entry in the config
file should have a colon, :, in it to delineate the entry and the value.
The config file you pasted looks fine, so not sure what's going on. Maybe
you have a newline somewhere in the config file that you removed when
pasting it here?

On Tue, Sep 22, 2015 at 3:27 PM, K00sKlust <notifications@github.com> wrote:

> Hey. Im have been using the TwitterFollowBot for a few days, and its
> amazing :) [image: :+1:] But now i got this error out of nothing. [image:
> :confused:] Am i doing something wrong? (sorry for my bad english
> sometimes)
>
> root@EeePcServer:/home/user/PythonScrypts/Twitterbot# python
>
> Python 2.7.6 (default, Jun 22 2015, 18:00:18)
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
>
> from TwitterFollowBot import TwitterBot
> my_bot = TwitterBot()
>
> Traceback (most recent call last):
> File "", line 1, in
> File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/*init*.py",
> line 42, in *init*
> self.bot_setup(config_file)
> File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/*init*.py",
> line 82, in bot_setup
> value = line[1].strip()
> IndexError: list index out of range
>
> config.txt (but i dont think thats the problem)
>
> OAUTH_TOKEN:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> OAUTH_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> CONSUMER_KEY:xxxxxxxxxxxxxxxxxxxxxxxxxx
> CONSUMER_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> TWITTER_HANDLE:xxxxxxxx
> ALREADY_FOLLOWED_FILE:already-followed.txt
> FOLLOWERS_FILE:followers.txt
> FOLLOWS_FILE:following.txt
> USERS_KEEP_FOLLOWING:
> USERS_KEEP_UNMUTED:
> USERS_KEEP_MUTED:
> FOLLOW_BACKOFF_MIN_SECONDS:3
> FOLLOW_BACKOFF_MAX_SECONDS:10
>
> I got around 1200 followers right now. Just trying to give usefull
> information :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/82>.
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by K00sKlust** [comment]
I fixed it! I had some whitespace atcthe end of the config file. Deleted it and it works fine now. Thanks for reacting so fast!

**Comment by zeroyjk** [comment]
How to Fix it?

**Comment by gersanchez** [comment]
@K00sKlust say this "I fixed it! I had some whitespace at the end of the config file. Deleted it and it works fine now." this works for me. try it @zeroyjk
