### ISSUE TITLE
Invalid or expired token.

### ISSUE THREAD

**Issue by Loaft** [rhiever/TwitterFollowBot#83]
I can follow and sync but when I run 'my_bot.auto_unfollow_nonfollowers()' it unfollows 1 user, and crashes. When i go to check my access tokens it seems they are revoked, and i have to re-create them. Anyone know why this is happening? I understand it might be a Twitter API problem, not sure why its happening only on unfollowing however.

**Comment by rhiever** [comment]
If you regularly find yourself hitting the Twitter API limit, that's
probably why.

Generally, Twitter is against automating follows, favs, and unfollows
through the API, which is also why they revoke API access sometimes. Why
they're against it yet provide the ability to do it through the API is
confusing to me...

On Tue, Sep 29, 2015 at 11:43 AM, Loaft <notifications@github.com> wrote:

> I can follow and sync but when I run 'my_bot.auto_unfollow_nonfollowers()'
> it unfollows 1 user, and crashes. When i go to check my access tokens it
> seems they are revoked, and i have to re-create them. Anyone know why this
> is happening? I understand it might be a Twitter API problem, not sure why
> its happening only on unfollowing however.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/83>.
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by Loaft** [comment]
Thanks for the fast reply, what do you suggest i do? Should I delete and make a new app or give it some time? I've also recently changed my app name and started using the 'post' function, not sure if it has something to do with it, but it seems too coincidental as i've been using ur script for a few months now.

**Comment by rhiever** [comment]
If they're shutting your bot town for following, faving, or unfollowing,
then you're probably SOL and should only use the bot to do actions other
than those three.

On Tue, Sep 29, 2015 at 11:53 AM, Loaft <notifications@github.com> wrote:

> Thanks for the fast reply, what do you suggest i do? Should I delete and
> make a new app or give it some time? I've also recently changed my app name
> and started using the 'post' function, not sure if it has something to do
> with it, but it seems too coincidental as i've been using ur script for a
> few months now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/83#issuecomment-144101543>
> .
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by Loaft** [comment]
It's just very weird that they would still allow me to follow 100+ accounts every 10 minutes or so. Thanks for the help, ill comment if anything changes.

**Comment by rl421403** [comment]
Twitter allow [certain number of requests](https://dev.twitter.com/rest/public/rate-limits) in 15 mins window. If you are following 100+ accounts every 15 mins, no wonder you are hitting rate limit very often. Be careful, if you are hitting rate limit very ofter then they will suspend/block you app as well as associated app.

The best solution is to divide your actions into many different apps. May be create 5-10 apps and use them for different actions.

For example I use 2 apps for auto fav, 3 apps for auto follow and unfollow. And 1 app for auto tweet.
