### ISSUE TITLE
Retweet - error "already retweeted this tweet"

### ISSUE THREAD

**Issue by sinbad13** [rhiever/TwitterFollowBot#88]
The function auto_rt() returns an error:
{u'errors': [{u'message': u'You have already retweeted this tweet.', u'code': 327}]}

Retweets are stored in the cache?

**Comment by rhiever** [comment]
Twitter tracks if you've already retweeted something. The TwitterFollowBot doesn't, but instead uses Twitter's error message to (hopefully) gracefully move on when a tweet has already been retweeted.
