### ISSUE TITLE
Getting this error?

### ISSUE THREAD

**Issue by reliefs** [rhiever/TwitterFollowBot#89]
Hi when i install on my pc it works fine but when i install on my server i get this error

error invalid command 'easy_install'

I have easy_install installed on my server

Fixed by installing
https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py

**Comment by rhiever** [comment]
Are you using pip to install it on your server?

On Tuesday, December 15, 2015, reliefs <notifications@github.com> wrote:

> Hi when i install on my pc it works fine but when i install on my server i
> get this error
>
> error invalid command 'easy_install'
>
> I have easy_install installed on my server
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/89>.
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by reliefs** [comment]
fixed it by installing
https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py

Thanks for the fast answer awesome you have made easy to use :)

**Comment by rhiever** [comment]
:+1:
