### ISSUE TITLE
Any suggestions?

### ISSUE THREAD

**Issue by 179skr** [rhiever/TwitterFollowBot#92]
So i am running the bot daily to auto follow and then unfollow, any suggestions on what time i should set both bots..the follow and unfollow bot...and the delay times i should add to each bot. my unfollowbot has a delay of 5-10 secs and starts 3 hours before my follow bot kicks in.

**Comment by rhiever** [comment]
Let's please redirect this chat to the repo gitter channel: https://gitter.im/rhiever/TwitterFollowBot
