### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by KISShii** [rhiever/TwitterFollowBot#93]
Thank you for your job.

I tried to install this.
But I got a problem.
Here is error code below.

python /home/web-kun/local/lib/python2.7/site-packages/TwitterFollowBot/__init__.py
  File "/home/web-kun/local/lib/python2.7/site-packages/TwitterFollowBot/__init__.py", line 78
    with open(config_file, "r") as in_file:
            ^
SyntaxError: invalid syntax

How can I solve it??

Regards,
Shota

**Comment by tatic0** [comment]
Hello, 


Please check the installation and examples on the wiki section:
https://github.com/rhiever/TwitterFollowBot/wiki

**Comment by rhiever** [comment]
If you're still having issues, please bring them up in the repo gitter: https://gitter.im/rhiever/TwitterFollowBot
