### ISSUE TITLE
Authenticating other users other than the owner

### ISSUE THREAD

**Issue by shanewignall** [rhiever/TwitterFollowBot#94]
I have absolutely zero experience when it comes to making applications that involve authentication. I basically have been working on a program using this (awesome) bot, but If I wanted to be able to have other users download this for their own use, how would the config file get set up? What exactly needs to happen?

**Comment by rhiever** [comment]
They would need to follow the [setup instructions](https://github.com/rhiever/TwitterFollowBot#dependencies) to set up API access on their account.

Let's please redirect this chat to the repo gitter channel: https://gitter.im/rhiever/TwitterFollowBot
