### ISSUE TITLE
posting of Images

### ISSUE THREAD

**Issue by Justin-Chaschowy** [rhiever/TwitterFollowBot#99]
Anything about posting images from the command line?

Either locally or by a hosted url

**Comment by rhiever** [comment]
I have another bot that does that. You can find that code here: https://github.com/rhiever/reddit-twitter-bot/blob/master/reddit_twitter_bot.py#L110

**Comment by Justin-Chaschowy** [comment]
thank you sir, very much appreciate all your work.
